openapi: 3.1.0
info:
  version: 1.0.0
  title: TODO Task Manager API
  contact:
    name: Daniel Osorio
    email: danioshi@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is the API definition for the TODO Task Manager API.

externalDocs:
  description: "Check out the GitHub repository."
  url: 'https://github.com/daniosoriov/todo-manager'
tags:
  - name: Auth
    description: "Authentication and authorization operations."
  - name: Task
    description: "Operations related to tasks."

servers:
  - url: http://localhost:{port}/v1.0
    description: Localhost Development Server
    variables:
      port:
        default: '3000'
        enum:
          - '80'
          - '3000'
paths:
  /auth/login:
    $ref: 'paths/auth/login.yaml'
  /auth/signup:
    $ref: 'paths/auth/register.yaml'
  /auth/refresh-token:
    $ref: 'paths/auth/refresh-token.yaml'
  /task:
    post:
      $ref: 'paths/task/create.yaml'
  /task/{taskId}:
    get:
      $ref: 'paths/task/get.yaml'
    put:
      $ref: 'paths/task/update.yaml'
    delete:
      $ref: 'paths/task/delete.yaml'

security:
  - BearerAuth: [ ]

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
